In [1]:
import pandas as pd

In [2]:
car = pd.read_csv('quikr_car.csv')

In [3]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

# **Cleaning**

In [4]:
backup = car.copy()

In [5]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [6]:
car= car[car['year'].str.isnumeric()]

In [7]:
car['year']= car['year'].astype(int)

<ipython-input-7-27f01879d805>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['year']= car['year'].astype(int)

In [8]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB

In [9]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '4,35,000', '1,89,700', '3,89,700', '3,60,000',
       '2,95,000', '1,14,990', '10,65,000', '4,70,000', '48,000',
       '1,88,000', '4,65,000', '1,79,999', '21,90,000', '23,90,000',
       '10,75,000', '4,75,000', '10,25,000', '6,15,000', '19,00,000',
       '14,90,000', '15,10,000', '18,50,000', '7,90,000', '17,25,000',
       '12,25,000', '68,000', '9,70,000', '31,00,000', '8,99,000',
       '88,000', '53,000', '5,68,500', '71,000', '5,90,000', '7,95,000',
       '42,000', '1,89,000', '1,62,000', '35,999', '29,00,000', '39,999',
       '50,500', '5,10,000', '8,60,000', '5,00,001'], dtype=object)

In [10]:
car= car[car['Price']!= 'Ask For Price']

In [11]:
car['Price']= car['Price'].str.replace(',', '').astype(int)

In [12]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [13]:
car['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  275000,  285000,  340000,   70000,  289999,
        849999,  749999,  274999,  984999,  599999,  244999,  474999,
        245000,  169500,  370000,  168000,  145000,   98500,  209000,
        185000,  900000,  699999,  199999,  544999,  199000,  540000,
         49000,  700000,   55000,  895000,  355000,  565000,  365000,
         40000,  400000,  330000,  580000,  379000,  219000,  519000,
        730000, 2000000, 2100000, 1400000,  311000,  855000,  535000,
        178000,  300000,  255000,  549999,  380000,   57000,  410000,
        225000,  120000,   59000,  599000,  675000,   72500,  610000,
        230000,  520000,  524999,  424999,  644999,  584999,  799999,
        444999,  649999,  944999,  574999,  374999,  130000,  401000,
       1350000,  174999,  239999,   99999,  324999, 1074999, 1130000,
        149000,  770000,   30000,  335000,  399000,   65000,  169999,
        165000,  560000,  950000,  715000,   45000,  940000,  155555,
       1500000,  495000,  800000, 1299000,  530000, 1499000,   32000,
        405000,  760000,  750000,  419000,  140000, 1540000,  123000,
        498000,  480000,  488000, 1525000,  548900,  725000,   99000,
         52000, 2800000,  499000,  381000,  278000,  690000,  260000,
         90001,  115000, 1599000,  159000,   51999,  215000,   35000,
       1150000,  269000,   60000,  430000, 8500003,  401919,  490000,
        424000,  205000,  549900,  435000,  189700,  389700,  360000,
        295000,  114990, 1065000,  470000,   48000,  188000,  465000,
        179999, 2190000, 2390000, 1075000,  475000, 1025000,  615000,
       1900000, 1490000, 1510000, 1850000,  790000, 1725000, 1225000,
         68000,  970000, 3100000,  899000,   88000,   53000,  568500,
         71000,  590000,  795000,   42000,  189000,  162000,   35999,
       2900000,   39999,   50500,  510000,  860000,  500001])

In [14]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64
 3   Price       819 non-null    int64
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB

In [15]:
car['company'].unique()

array(['Hyundai', 'Mahindra', 'Ford', 'Maruti', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Land', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [16]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '28,000 kms', '36,000 kms', '41,000 kms',
       '25,000 kms', '24,530 kms', '60,000 kms', '30,000 kms',
       '32,000 kms', '48,660 kms', '4,000 kms', '16,934 kms',
       '43,000 kms', '35,550 kms', '39,522 kms', '39,000 kms',
       '55,000 kms', '72,000 kms', '15,975 kms', '70,000 kms',
       '23,452 kms', '35,522 kms', '48,508 kms', '15,487 kms',
       '82,000 kms', '20,000 kms', '68,000 kms', '38,000 kms',
       '27,000 kms', '33,000 kms', '46,000 kms', '16,000 kms',
       '47,000 kms', '35,000 kms', '30,874 kms', '15,000 kms',
       '29,685 kms', '1,30,000 kms', '19,000 kms', '54,000 kms',
       '13,000 kms', '38,200 kms', '22,000 kms', '50,000 kms',
       '13,500 kms', '3,600 kms', '45,863 kms', '60,500 kms',
       '12,500 kms', '18,000 kms', '13,349 kms', '29,000 kms',
       '44,000 kms', '42,000 kms', '14,000 kms', '49,000 kms',
       '36,200 kms', '51,000 kms', '1,04,000 kms', '33,333 kms',
       '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms', '24,330 kms',
       '65,480 kms', '2,00,000 kms', '59,000 kms', '99,000 kms',
       '2,800 kms', '21,000 kms', '11,000 kms', '66,000 kms', '3,000 kms',
       '7,000 kms', '38,500 kms', '37,200 kms', '43,200 kms',
       '24,800 kms', '45,872 kms', '40,000 kms', '11,400 kms',
       '97,200 kms', '52,000 kms', '31,000 kms', '1,75,430 kms',
       '37,000 kms', '65,000 kms', '3,350 kms', '75,000 kms',
       '62,000 kms', '73,000 kms', '2,200 kms', '54,870 kms',
       '34,580 kms', '97,000 kms', '60 kms', '80,200 kms', '3,200 kms',
       '0,000 kms', '5,000 kms', '588 kms', '71,200 kms', '1,75,400 kms',
       '9,300 kms', '56,758 kms', '10,000 kms', '56,450 kms',
       '56,000 kms', '32,700 kms', '9,000 kms', '73 kms', '1,60,000 kms',
       '58,559 kms', '57,000 kms', '1,70,000 kms', '80,000 kms',
       '6,821 kms', '23,000 kms', '34,000 kms', '1,800 kms',
       '4,00,000 kms', '48,000 kms', '90,000 kms', '12,000 kms',
       '69,900 kms', '1,66,000 kms', '122 kms', '0 kms', '36,469 kms',
       '7,800 kms', '24,695 kms', '15,141 kms', '59,910 kms',
       '1,00,000 kms', '4,500 kms', '1,29,000 kms', '300 kms',
       '1,31,000 kms', '1,11,111 kms', '59,466 kms', '25,500 kms',
       '44,005 kms', '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '53,000 kms', '35,500 kms', '22,134 kms',
       '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms', '8,000 kms',
       '55,800 kms', '56,400 kms', '72,160 kms', '11,500 kms',
       '1,33,000 kms', '2,000 kms', '88,000 kms', '65,422 kms',
       '1,17,000 kms', '1,50,000 kms', '10,750 kms', '6,800 kms',
       '9,800 kms', '57,923 kms', '30,201 kms', '6,200 kms', '37,518 kms',
       '24,652 kms', '383 kms', '95,000 kms', '3,528 kms', '52,500 kms',
       '47,900 kms', '52,800 kms', '1,95,000 kms', '48,008 kms',
       '48,247 kms', '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '1,37,495 kms',
       '91,200 kms', '1,46,000 kms', '1,00,800 kms', '2,100 kms',
       '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [17]:
car['kms_driven']= car['kms_driven'].str.split(' ').str.get(0).str.replace(',', '')

In [18]:
car=car[car['kms_driven']!= 'Petrol']

In [19]:
car['kms_driven']= car['kms_driven'].astype(int)

<ipython-input-19-ed316f6d7453>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['kms_driven']= car['kms_driven'].astype(int)

In [20]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.7+ KB

In [21]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [22]:
car = car[~car['fuel_type'].isna()]

In [23]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [24]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [25]:
car['name'].unique()

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Maruti Suzuki Alto 800 Vxi', 'Hyundai i20 Sportz 1.2',
       'Maruti Suzuki Alto 800 Lx', 'Maruti Suzuki Vitara Brezza ZDi',
       'Maruti Suzuki Alto LX', 'Mahindra Bolero DI',
       'Maruti Suzuki Swift Dzire ZDi', 'Mahindra Scorpio S10 4WD',
       'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maruti Suzuki Baleno Delta 1.2',
       'Renault Duster 110 PS RxZ Diesel Plus',
       'Renault Duster 85 PS RxE Diesel', 'Honda City 1.5 S MT',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5 SX i DTEC',
       'Honda City', 'Datsun Redi GO S', 'Maruti Suzuki SX4 ZXI MT',
       'Mitsubishi Pajero Sport Limited Edition',
       'Maruti Suzuki Swift VXi 1.2 ABS BS IV', 'Honda City ZX CVT',
       'Maruti Suzuki Wagon R LX BS IV', 'Tata Indigo eCS LS CR4 BS IV',
       'Volkswagen Polo Highline Exquisite P', 'Chevrolet Spark LS 1.0',
       'Renault Duster 110PS Diesel RxZ', 'Mini Cooper S 1.6',
       'Skoda Fabia 1.2L Diesel Ambiente', 'Renault Duster',
       'Mahindra Scorpio S4', 'Mahindra Scorpio VLX 2WD BS IV',
       'Mahindra Quanto C8', 'Ford EcoSport', 'Honda Brio',
       'Volkswagen Vento Highline Plus 1.5 Diesel AT',
       'Hyundai i20 Magna', 'Toyota Corolla Altis Diesel D4DG',
       'Hyundai Verna Transform SX VTVT',
       'Toyota Corolla Altis Petrol Ltd', 'Honda City 1.5 EXi New',
       'Skoda Fabia 1.2L Diesel Elegance', 'BMW 3 Series 320i',
       'Maruti Suzuki A Star Lxi', 'Toyota Etios GD',
       'Ford Figo Diesel EXI Option',
       'Maruti Suzuki Swift Dzire VXi 1.2 BS IV',
       'Chevrolet Beat LT Diesel', 'BMW 7 Series 740Li Sedan',
       'Mahindra XUV500 W8 AWD 2013', 'Hyundai i10 Magna 1.2',
       'Hyundai Verna Fluidic New', 'Maruti Suzuki Swift VXi 1.2 BS IV',
       'Maruti Suzuki Ertiga ZXI Plus', 'Maruti Suzuki Ertiga Vxi',
       'Maruti Suzuki Ertiga VDi', 'Maruti Suzuki Alto LXi BS III',
       'Hyundai Grand i10 Asta 1.1 CRDi', 'Honda Amaze 1.2 S i VTEC',
       'Hyundai i20 Asta 1.4 CRDI 6 Speed', 'Ford Figo Diesel EXI',
       'Maruti Suzuki Eeco 5 STR WITH AC HTR', 'Maruti Suzuki Ertiga ZXi',
       'Maruti Suzuki Esteem LXi BS III', 'Maruti Suzuki Ritz VXI',
       'Maruti Suzuki Ritz LDi', 'Maruti Suzuki Dzire VDI',
       'Toyota Etios Liva G', 'Hyundai i20 Sportz 1.4 CRDI',
       'Chevrolet Spark', 'Nissan Micra XV', 'Maruti Suzuki Swift',
       'Honda Amaze 1.5 S i DTEC', 'Chevrolet Beat',
       'Honda City 1.5 V MT', 'Ford EcoSport Trend 1.5L TDCi',
       'Hyundai i20 Asta 1.2', 'Tata Indica V2 eLS',
       'Hindustan Motors Ambassador', 'Toyota Corolla Altis 1.8 GL',
       'Toyota Corolla Altis 1.8 J', 'Toyota Innova 2.5 GX BS IV 7 STR',
       'Volkswagen Jetta Highline TDI AT',
       'Volkswagen Polo Comfortline 1.2L P', 'Volkswagen Polo',
       'Mahindra Scorpio', 'Nissan Sunny', 'Hyundai Elite i20',
       'Renault Kwid', 'Mahindra Scorpio VLX Airbag',
       'Maruti Suzuki Alto 800 Lxi', 'Chevrolet Spark LT 1.0',
       'Datsun Redi GO T O', 'Maruti Suzuki Swift RS VDI',
       'Fiat Punto Emotion 1.2', 'Hyundai i10 Sportz 1.2',
       'Chevrolet Beat LT Opt Diesel', 'Chevrolet Beat LS Diesel',
       'Tata Indigo CS', 'Maruti Suzuki Swift VDi',
       'Hyundai Eon Era Plus', 'Mahindra XUV500', 'Ford Fiesta',
       'Maruti Suzuki Wagon R', 'Hyundai i20',
       'Tata Indigo eCS LX TDI BS III',
       'Hyundai Fluidic Verna 1.6 CRDi SX', 'Fiat Petra ELX 1.2 PS',
       'Hyundai Santro Xing XS', 'Maruti Suzuki Ciaz VXi Plus',
       'Maruti Suzuki Zen VX', 'Hyundai Creta 1.6 SX Plus Petrol',
       'Mahindra Scorpio SLX', 'Toyota Innova 2.5 G BS III 8 STR',
       'Maruti Suzuki Wagon R LXI BS IV', 'Tata Nano Cx BSIV',
       'Maruti Suzuki Alto Std BS IV', 'Maruti Suzuki Wagon R LXi BS III',
       'Maruti Suzuki Swift VXI BSIII',
       'Tata Sumo Victa EX 10 by 7 Str BSIII',
       'Volkswagen Passat Diesel Comfortline AT',
       'Renault Scala RxL Diesel Travelogue',
       'Hyundai Grand i10 Sportz O 1.2 Kappa VTVT',
       'Hyundai i20 Active 1.2 SX', 'Mahindra Xylo E4',
       'Mahindra Jeep MM 550 XDB', 'Mahindra Bolero SLE BS IV',
       'Force Motors Force One LX ABS 7 STR', 'Maruti Suzuki SX4',
       'Toyota Etios', 'Honda City ZX VTEC',
       'Maruti Suzuki Wagon R LX BS III', 'Honda City VX O MT Diesel',
       'Mahindra Thar CRDe 4x4 AC',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Mercedes Benz GLA Class 200 CDI Sport',
       'Land Rover Freelander 2 SE', 'Renault Kwid RXT',
       'Tata Aria Pleasure 4X2', 'Mercedes Benz B Class B180 Sports',
       'Datsun GO T O', 'Honda Jazz VX MT',
       'Hyundai i20 Active 1.4L SX O', 'Mini Cooper S',
       'Maruti Suzuki Ciaz ZXI Plus', 'Chevrolet Tavera Neo',
       'Hyundai Eon Sportz', 'Tata Sumo Gold Select Variant',
       'Maruti Suzuki Wagon R 1.0', 'Maruti Suzuki Esteem VXi BS III',
       'Chevrolet Enjoy 1.4 LS 8 STR', 'Maruti Suzuki Wagon R 1.0 VXi',
       'Nissan Terrano XL D Plus', 'Renault Duster 85 PS RxL Diesel',
       'Maruti Suzuki Dzire ZXI', 'Renault Kwid RXT Opt',
       'Maruti Suzuki Maruti 800 Std', 'Renault Kwid 1.0 RXT AMT',
       'Renault Scala RxL Diesel',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT O',
       'Chevrolet Beat LS Petrol', 'Hyundai Accent GLX',
       'Mahindra TUV300 T4 Plus', 'Tata Indica V2 Xeta e GLE',
       'Tata Indigo CS LS DiCOR',
       'Mahindra Scorpio VLX Special Edition BS III', 'Honda Accord',
       'Ford EcoSport Titanium 1.5 TDCi', 'Maruti Suzuki Ertiga',
       'Mahindra Scorpio 2.6 CRDe', 'Honda Mobilio',
       'Toyota Corolla Altis', 'Skoda Laura', 'Hyundai Verna Fluidic',
       'Maruti Suzuki Vitara Brezza', 'Tata Manza Aura Quadrajet',
       'Chevrolet Sail UVA Petrol LT ABS',
       'Hyundai Verna Fluidic 1.6 VTVT SX',
       'Audi A4 2.0 TDI 177bhp Premium', 'Hyundai Elantra SX',
       'Mahindra Scorpio VLX 4WD Airbag', 'Mahindra KUV100 K8 D 6 STR',
       'Hyundai Grand i10', 'Hyundai i10', 'Hyundai i20 Active',
       'Datsun Redi GO', 'Toyota Etios Liva', 'Hyundai Accent',
       'Hyundai Verna', 'Toyota Fortuner', 'Hyundai i10 Sportz',
       'Mahindra Bolero Power Plus SLE', 'Honda City 1.5 V MT Exclusive',
       'Chevrolet Spark LT 1.0 Airbag', 'Tata Indigo eCS VX CR4 BS IV',
       'Skoda Rapid Elegance 1.6 TDI CR MT', 'Tata Vista Quadrajet VX',
       'Maruti Suzuki Alto K10 VXi AT', 'Maruti Suzuki Zen LXi BS III',
       'Maruti Suzuki Swift Dzire Tour LDi', 'Honda City ZX EXi',
       'Chevrolet Beat Diesel', 'Hyundai Verna 1.4 VTVT',
       'Toyota Innova 2.5 E MS 7 STR BS IV',
       'Maruti Suzuki Maruti 800 Std – Befo',
       'Hyundai Elite i20 Asta 1.4 CRDI',
       'Maruti Suzuki Versa DX2 8 SEATER BSIII',
       'Tata Indigo LX TDI BS III',
       'Volkswagen Vento Konekt Diesel Highline',
       'Mercedes Benz C Class 200 CDI Classic', 'Hyundai Santro Xing GLS',
       'Maruti Suzuki Omni Limited Edition',
       'Hyundai Sonata Transform 2.4 GDi MT',
       'Hyundai Elite i20 Sportz 1.2', 'Honda Jazz S MT',
       'Hyundai Grand i10 Sportz 1.2 Kappa VTVT',
       'Maruti Suzuki Zen LXi BSII',
       'Mahindra Scorpio W Turbo 2.6DX 9 Seater',
       'Maruti Suzuki Alto K10 VXi',
       'Hyundai Grand i10 Asta 1.2 Kappa VTVT', 'Mahindra XUV500 W8',
       'Hyundai i20 Magna O 1.2', 'Renault Duster 85 PS RxL Explore LE',
       'Honda Brio V MT', 'Mahindra TUV300 T8',
       'Nissan X Trail Select Variant', 'Ford Ikon 1.3 CLXi NXt Finesse',
       'Toyota Fortuner 3.0 4x4 MT', 'Tata Manza ELAN Quadrajet',
       'Mercedes Benz A Class A 180 Sport Petrol', 'Tata Indigo LS',
       'Hyundai i20 Magna 1.2', 'Honda Amaze 1.5 E i DTEC',
       'Hyundai Verna 1.6 EX VTVT', 'BMW 5 Series 520d Sedan',
       'Skoda Superb 1.8 TFSI AT', 'Audi Q3 2.0 TDI quattro Premium',
       'Mahindra Bolero DI BSII',
       'Ford Figo Duratorq Diesel Titanium 1.4',
       'Maruti Suzuki Wagon R VXI BS IV', 'Mahindra Logan Diesel 1.5 DLS',
       'Tata Nano GenX XMA', 'Honda City SV', 'Ford Figo Petrol LXI',
       'Hyundai i10 Magna 1.2 Kappa2', 'Toyota Corolla H2',
       'Maruti Suzuki Swift Dzire Tour VXi', 'Tata Indigo CS eLS BS IV',
       'Hyundai Xcent Base 1.1 CRDi', 'Hyundai Accent Executive Edition',
       'Tata Zest XE 75 PS Diesel', 'Maruti Suzuki Dzire LDI',
       'Tata Sumo Gold LX BS IV', 'Toyota Corolla Altis GL Petrol',
       'Maruti Suzuki Eeco 7 STR', 'Toyota Fortuner 3.0 4x2 MT',
       'Mahindra XUV500 W6', 'Tata Tigor Revotron XZ',
       'Maruti Suzuki 800', 'Honda Mobilio S i DTEC',
       'Hyundai Verna 1.6 CRDI E', 'Maruti Suzuki Omni Select Variant',
       'Tata Indica', 'Hyundai Santro Xing', 'Maruti Suzuki Zen Estilo',
       'Honda Brio VX AT', 'Maruti Suzuki Zen Estilo LXI Green CNG',
       'Maruti Suzuki Wagon R Select Variant', 'Tata Nano Lx BSIV',
       'Jaguar XE XE Portfolio', 'Hyundai Eon Magna Plus',
       'Maruti Suzuki Ritz GENUS VXI',
       'Hyundai Grand i10 Magna AT 1.2 Kappa VTVT',
       'Hyundai Eon D Lite Plus', 'Honda Amaze 1.2 VX i VTEC',
       'Maruti Suzuki Estilo VXi ABS BS IV',
       'Maruti Suzuki Vitara Brezza LDi O',
       'Hyundai Creta 1.6 SX Plus Petrol AT', 'Mahindra Scorpio Vlx BSIV',
       'Mitsubishi Lancer 1.8 LXi', 'Maruti Suzuki Maruti 800 AC',
       'Maruti Suzuki Alto 800 LXI CNG O', 'Ford Fiesta SXi 1.6 ABS',
       'Maruti Suzuki Ritz VDi', 'Maruti Suzuki Estilo LX BS IV',
       'Audi A6 2.0 TDI Premium', 'Maruti Suzuki Alto',
       'Maruti Suzuki Baleno Sigma 1.2', 'Hyundai Verna 1.6 SX VTVT AT',
       'Maruti Suzuki Swift GLAM', 'Hyundai Getz Prime 1.3 GVS',
       'Hyundai Santro', 'Hyundai Getz Prime 1.3 GLX',
       'Chevrolet Beat PS Diesel', 'Ford EcoSport Trend 1.5 Ti VCT',
       'Tata Indica V2 DLG', 'BMW X1 xDrive20d xLine',
       'Honda City 1.5 V AT', 'Tata Nano', 'Chevrolet Cruze LTZ AT',
       'Maruti Suzuki Swift Dzire VDi', 'Mahindra XUV500 W10',
       'Maruti Suzuki Alto K10 LXi CNG', 'Hyundai Accent GLE',
       'Force Motors One SUV', 'Chevrolet Spark 1.0 LT',
       'Toyota Etios Liva GD',
       'Renault Duster 85PS Diesel RxL Optional with Nav',
       'Chevrolet Enjoy', 'BMW 5 Series 530i', 'Chevrolet Cruze LTZ',
       'Jeep Wrangler Unlimited 4x4 Diesel',
       'Hyundai Verna VGT CRDi SX ABS', 'Maruti Suzuki Omni',
       'Maruti Suzuki Celerio VDi', 'Tata Zest Quadrajet 1.3',
       'Tata Indigo CS eLX BS IV', 'Hyundai i10 Era',
       'Tata Indigo eCS LX CR4 BS IV', 'Tata Indigo Marina LS',
       'Hyundai Xcent SX 1.2', 'Tata Nano LX Special Edition',
       'Renault Duster 110 PS RxZ Diesel',
       'Maruti Suzuki Wagon R AX BSIV', 'Maruti Suzuki Alto K10 New',
       'Mahindra Xylo E8', 'Tata Manza Aqua Quadrajet',
       'Renault Kwid 1.0', 'Tata Venture EX 8 STR',
       'Maruti Suzuki Swift Dzire Tour LXi',
       'Skoda Octavia Classic 1.9 TDI MT', 'Maruti Suzuki Omni LPG BS IV',
       'Tata Sumo Gold EX BS IV', 'Hyundai Verna 1.6 CRDI SX',
       'Mahindra Scorpio SLX 2.6 Turbo 8 Str', 'Ford Ikon 1.6 Nxt',
       'Toyota Innova 2.5 V 7 STR', 'Nissan Sunny XL',
       'Maruti Suzuki Swift VDi BS IV', 'Toyota Innova 2.0 G4',
       'Maruti Suzuki Swift VDi ABS', 'Hyundai Elite i20 Asta 1.2',
       'Volkswagen Polo Trendline 1.5L D', 'Toyota Etios Liva Diesel',
       'Maruti Suzuki Ciaz ZXi Plus RS', 'Hyundai Elantra 1.8 S',
       'Ford EcoSport Trend 1.5L Ti VCT', 'Tata Indica eV2 LS',
       'Jaguar XF 2.2 Diesel Luxury',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'BMW 3 Series 320d Sedan',
       'Maruti Suzuki Swift ZXi 1.2 BS IV', 'BMW X1 sDrive20d',
       'Maruti Suzuki S Cross Sigma 1.3', 'Maruti Suzuki Ertiga LDi',
       'Volkswagen Vento Comfortline Petrol', 'Mahindra KUV100',
       'Maruti Suzuki Swift Dzire Tour VDi', 'Mahindra Scorpio 2.6 SLX',
       'Maruti Suzuki Omni 8 STR BS III',
       'Volkswagen Jetta Comfortline 1.9 TDI AT', 'Volvo S80 Summum D4',
       'Toyota Corolla Altis VL AT Petrol',
       'Mitsubishi Pajero Sport 2.5 AT', 'Chevrolet Beat LT Petrol',
       'BMW X1', 'Mercedes Benz C Class C 220 CDI Avantgarde',
       'Volkswagen Vento Comfortline Diesel', 'Tata Indigo CS GLS',
       'Ford Figo Petrol Titanium', 'Honda City ZX GXi',
       'Maruti Suzuki Wagon R Duo Lxi', 'Maruti Suzuki Zen LX BSII',
       'Renault Duster RxL Petrol', 'Maruti Suzuki Baleno Zeta 1.2',
       'Honda WR V S MT Petrol', 'Renault Duster 110 PS RxL Diesel',
       'Mahindra Scorpio LX BS III',
       'Maruti Suzuki SX4 Celebration Diesel',
       'Audi A3 Cabriolet 40 TFSI', 'Hyundai Santro AE GLS Audio',
       'Mahindra Xylo D2 BS IV', 'Hyundai Getz GLE',
       'Hyundai Creta 1.6 SX', 'Hyundai Santro Xing XL AT eRLX Euro III',
       'Hyundai Santro Xing XL eRLX Euro III',
       'Tata Indica V2 DLS BS III', 'Honda City 1.5 E MT',
       'Nissan Micra XL', 'Honda City 1.5 S Inspire',
       'Tata Indica eV2 eXeta eGLX', 'Maruti Suzuki Omni E 8 STR BS IV',
       'Maruti Suzuki Swift LDi', 'Hyundai Verna 1.6 CRDI SX Plus AT',
       'Chevrolet Tavera LS B3 10 Seats BSII', 'Tata Tiago Revotron XM',
       'Tata Tiago Revotorq XZ',
       'Hindustan Motors Ambassador Classic Mark 4 – Befo',
       'Ford Fusion 1.4 TDCi Diesel',
       'Fiat Linea Emotion 1.4 L T Jet Petrol',
       'Ford Ikon 1.3 Flair Josh 100', 'Tata Indica V2 LS',
       'Mahindra Xylo D2', 'Toyota Corolla', 'Hyundai Eon Magna',
       'Tata Sumo Grande MKII GX', 'Volkswagen Polo Highline1.2L P',
       'Tata Tiago Revotron XZ', 'Tata Indigo eCS',
       'Mahindra Xylo E8 BS IV', 'Tata Sumo Gold FX BSIII',
       'Hyundai Creta', 'Tata Bolt XM Petrol', 'Maruti Suzuki Ritz',
       'Hyundai i20 Asta', 'Maruti Suzuki Swift Select Variant',
       'Tata Indica V2 DLX BS III',
       'Mahindra Scorpio VLX 2.2 mHawk Airbag BSIV',
       'Toyota Innova 2.5 E 8 STR', 'Mahindra KUV100 K8 6 STR',
       'Datsun Go Plus', 'Ford Endeavor 4x4 Thunder Plus',
       'Tata Indica V2', 'Hyundai Santro Xing GL',
       'Toyota Innova 2.5 Z Diesel 7 Seater', 'Maruti Suzuki Alto AX',
       'Mahindra Logan', 'Maruti Suzuki 800 Std BS III',
       'Chevrolet Sail 1.2 LS', 'Tata Manza', 'Toyota Etios G',
       'Toyota Qualis', 'Mahindra Quanto C4', 'Maruti Suzuki Swift Dzire',
       'Hyundai i20 Select Variant', 'Honda City VX Petrol',
       'Hyundai Getz', 'Mercedes Benz C Class 200 K MT', 'Skoda Fabia',
       'Maruti Suzuki Ritz VXI ABS', 'Tata Indica V2 DLE BS III',
       'Tata Zest XM Diesel'], dtype=object)

In [26]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [27]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    int64
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [28]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [29]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [30]:
car[car['Price']>=6e6]

                   name   company  year    Price  kms_driven fuel_type
562  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [31]:
car=car[car['Price']<=6e6]

In [32]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 815 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        815 non-null    object
 1   company     815 non-null    object
 2   year        815 non-null    int64
 3   Price       815 non-null    int64
 4   kms_driven  815 non-null    int64
 5   fuel_type   815 non-null    object
dtypes: int64(3), object(3)
memory usage: 44.6+ KB

In [33]:
car.describe()

              year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [34]:
car[car['Price']>=2.3e6]

                  name company  year    Price  kms_driven fuel_type
510       Jaguar XE XE  Jaguar  2016  2800000        8500    Petrol
668        Audi Q5 2.0    Audi  2014  2390000       34000    Diesel
719  Audi A3 Cabriolet    Audi  2015  3100000       12516    Petrol
838  Ford Endeavor 4x4    Ford  2019  2900000        9000    Diesel

In [35]:
car.reset_index(drop=True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [36]:
car.to_csv('Cleaned car.csv')

# Model

In [37]:
X = car.drop(columns= 'Price')
y = car['Price']

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [39]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
import numpy as np

In [40]:
ohe = OneHotEncoder()
ohe.fit(X[['name', 'company', 'fuel_type']])

OneHotEncoder()

In [41]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [42]:
lr = LinearRegression()

In [43]:
transformer = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder = 'passthrough')

In [44]:
pipe = make_pipeline(transformer,lr)

In [45]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [46]:
y_pred = pipe.predict(X_test)

In [47]:
y_pred

array([ 2.49654986e+05,  3.12420200e+05,  2.45524551e+05,  4.36989613e+05,
        1.97940852e+06,  6.61800714e+05,  4.49275315e+05,  2.06122837e+05,
        3.53912167e+05,  9.73409016e+04,  3.79594242e+05,  1.26828474e+05,
        3.29623882e+05,  5.94096519e+05,  2.14099491e+05,  5.68773021e+05,
        2.92198612e+05,  4.97120644e+05,  4.36191951e+05,  2.03376497e+05,
        2.22080562e+05,  3.64679519e+05,  2.08375158e+05,  3.36931970e+05,
        2.07896233e+05,  5.60306501e+05, -4.81227148e+02,  5.45179994e+05,
        5.98246811e+05,  4.29234265e+05,  1.04404409e+06,  7.67844609e+05,
        2.83012769e+05,  2.49663755e+05,  4.17194096e+05,  4.93366256e+05,
        3.35418082e+05,  7.29023568e+05,  3.37197442e+05,  3.25549834e+05,
       -5.29807582e+04,  5.98195809e+05,  3.20411790e+05,  5.21665937e+05,
        1.97940852e+06,  1.98025574e+05,  3.90380980e+05,  2.68829089e+05,
        5.76343494e+05,  3.39256694e+05,  2.48524419e+05,  3.26633372e+05,
        3.52022659e+05,  7.62307148e+05,  4.12902332e+05,  1.51021459e+05,
        2.88966336e+05,  1.69185526e+05,  1.58308370e+05,  2.21289459e+05,
        4.38187352e+05,  5.07681883e+05,  3.70756946e+05,  2.85024501e+05,
        5.94857727e+05,  2.24948773e+04,  4.27414962e+05,  4.71779612e+05,
        3.11502881e+05,  6.37915827e+05,  4.32158934e+05,  3.29623882e+05,
        5.99949638e+05,  3.17986237e+05,  5.38001402e+05,  1.97940852e+06,
        4.34098196e+05,  3.01327155e+05,  4.49164501e+05,  6.01151324e+05,
        2.07389528e+05,  9.63080601e+04,  2.29262919e+05,  4.91494912e+05,
        2.93563877e+05,  5.14539422e+05,  2.94712900e+05,  1.86764077e+05,
        4.37471361e+04,  6.24918816e+05,  5.03643237e+05,  3.99252228e+05,
        1.59471719e+05,  3.99488696e+05,  4.92539153e+05,  5.87633344e+05,
       -1.11869850e+04,  2.50255561e+05,  1.82934622e+06,  7.80060248e+05,
        4.70390463e+05,  6.46548276e+05,  5.77480467e+05,  2.97020175e+05,
        4.07997430e+05,  2.21626292e+05,  3.85672674e+04,  5.65036650e+05,
        4.04059931e+05,  5.70236436e+05,  2.38580064e+05,  3.15357679e+05,
        2.87650570e+05,  2.08470348e+05,  5.04526132e+05,  5.78009814e+05,
        4.85129175e+05,  7.98847960e+04,  3.10499234e+05,  1.75527869e+05,
        7.89618859e+04,  1.89753468e+05,  5.53562601e+05,  2.84978655e+05,
        1.01151025e+06,  3.70671837e+04,  3.14975348e+05,  4.04824618e+05,
        7.17779769e+05,  5.82695723e+05,  6.06182973e+05,  5.15615566e+05,
        3.60679497e+05,  9.65051367e+03,  4.18525863e+05, -1.98342726e+04,
        2.14649944e+05,  1.97917779e+06,  1.34971341e+05,  5.06738270e+05,
        1.51188778e+05,  3.90156474e+05,  3.86002595e+05,  2.67782766e+05,
        3.27826199e+05,  5.04118491e+04,  4.13919624e+05,  7.94341500e+05,
        2.60750389e+05,  5.87811106e+05,  2.75875436e+05,  6.36430657e+05,
        2.22847333e+05,  3.01761552e+05,  1.99871394e+05,  2.70325686e+05,
        4.01174935e+05,  4.59002661e+05,  3.45390988e+05,  2.37495867e+05,
        2.72519368e+05,  2.38481918e+05,  5.26495296e+05])

In [48]:
r2_score(y_test,y_pred)

0.7303755751951004

In [49]:
score=[]
for i in range(2000):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(transformer,lr)
    pipe.fit(X_train,y_train)
    y_pred = pipe.predict(X_test)
    score.append(r2_score(y_test,y_pred))

In [50]:
np.argmax(score)

433

In [51]:
score[np.argmax(score)]

0.8457059012561223

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state = np.argmax(score))
lr = LinearRegression()
pipe = make_pipeline(transformer,lr)
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)

In [53]:
r2_score(y_test,y_pred)

0.8457059012561223

In [54]:
import pickle

In [55]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))